version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ratasy_app
    ports:
      - 8989:80
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - db

  db:
    image: mariadb:11.4
    container_name: ratasy_db
    environment:
      MYSQL_ROOT_PASSWORD: "mariadb#$$607756o"
      MYSQL_DATABASE: ratasy
      MYSQL_USER: root
      MYSQL_PASSWORD: "mariadb#$$607756o"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:
    driver: local
